### ISSUE TITLE
Highpoint HPT370 array shows up as two separate drives, can't partition correctly because of it and it errors during install. 

### ISSUE THREAD

**Issue by Kothnaaken** [oerg866/win98-quickinstall#13]
I'm trying to install on a system with a KT7A-Raid motherboard with a HPT370 chip that I have tried both raid 0 and 1 on, even without an array set up. Trying with a 0 set up will break up the array and with a raid 1 it will install to one drive causing an error on next boot but won't boot unless I manually select the second drive using a boot manager and even then I'll get an error of missing cat files as it boots up. I'm using the reference image(s) on archive.org in this case so I'm not sure if just building my own might help here? I've tried burning a dvd, cd and even usb booting but they all end up giving me the same result one way or another. 
![IMG_20240920_162711](https://github.com/user-attachments/assets/c1b8264d-3b9a-49ef-bc53-673783f85e38)

**Comment by oerg866** [comment]
Hi,

the image you attached was from 0.9.4 with a memory corruption bug that was fixed, but the ISOs with this fix are not yet released :( so all I can do is ask you to wait, the release for 0.9.4b is scheduled for next week.

The other thing about RAIDs is yes, since I don't use RAIDs I never tested them and it turns out the kernel is compiled without RAID support. I will check if I can make this work.

**Comment by oerg866** [comment]
Should be fixed in 0.9.5. I will upload new ISOs as soon as I can figure out where because archive.org is down...
